//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MatchRedux
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReduxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReduxEntities object using the connection string found in the 'ReduxEntities' section of the application configuration file.
        /// </summary>
        public ReduxEntities() : base("name=ReduxEntities", "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReduxEntities object.
        /// </summary>
        public ReduxEntities(string connectionString) : base(connectionString, "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReduxEntities object.
        /// </summary>
        public ReduxEntities(EntityConnection connection) : base(connection, "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gap> gaps
        {
            get
            {
                if ((_gaps == null))
                {
                    _gaps = base.CreateObjectSet<gap>("gaps");
                }
                return _gaps;
            }
        }
        private ObjectSet<gap> _gaps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<partialschedulematch> partialschedulematches
        {
            get
            {
                if ((_partialschedulematches == null))
                {
                    _partialschedulematches = base.CreateObjectSet<partialschedulematch>("partialschedulematches");
                }
                return _partialschedulematches;
            }
        }
        private ObjectSet<partialschedulematch> _partialschedulematches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pips_programmes> pips_programmes
        {
            get
            {
                if ((_pips_programmes == null))
                {
                    _pips_programmes = base.CreateObjectSet<pips_programmes>("pips_programmes");
                }
                return _pips_programmes;
            }
        }
        private ObjectSet<pips_programmes> _pips_programmes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_items> redux_items
        {
            get
            {
                if ((_redux_items == null))
                {
                    _redux_items = base.CreateObjectSet<redux_items>("redux_items");
                }
                return _redux_items;
            }
        }
        private ObjectSet<redux_items> _redux_items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_to_pips> redux_to_pips
        {
            get
            {
                if ((_redux_to_pips == null))
                {
                    _redux_to_pips = base.CreateObjectSet<redux_to_pips>("redux_to_pips");
                }
                return _redux_to_pips;
            }
        }
        private ObjectSet<redux_to_pips> _redux_to_pips;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_to_pipstoo> redux_to_pipstoo
        {
            get
            {
                if ((_redux_to_pipstoo == null))
                {
                    _redux_to_pipstoo = base.CreateObjectSet<redux_to_pipstoo>("redux_to_pipstoo");
                }
                return _redux_to_pipstoo;
            }
        }
        private ObjectSet<redux_to_pipstoo> _redux_to_pipstoo;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogaps(gap gap)
        {
            base.AddObject("gaps", gap);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the partialschedulematches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopartialschedulematches(partialschedulematch partialschedulematch)
        {
            base.AddObject("partialschedulematches", partialschedulematch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pips_programmes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopips_programmes(pips_programmes pips_programmes)
        {
            base.AddObject("pips_programmes", pips_programmes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_items(redux_items redux_items)
        {
            base.AddObject("redux_items", redux_items);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_to_pips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_to_pips(redux_to_pips redux_to_pips)
        {
            base.AddObject("redux_to_pips", redux_to_pips);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_to_pipstoo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_to_pipstoo(redux_to_pipstoo redux_to_pipstoo)
        {
            base.AddObject("redux_to_pipstoo", redux_to_pipstoo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="gap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gap object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static gap Creategap(global::System.Int32 id)
        {
            gap gap = new gap();
            gap.id = id;
            return gap;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> programme_id
        {
            get
            {
                return _programme_id;
            }
            set
            {
                Onprogramme_idChanging(value);
                ReportPropertyChanging("programme_id");
                _programme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("programme_id");
                Onprogramme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _programme_id;
        partial void Onprogramme_idChanging(Nullable<global::System.Int32> value);
        partial void Onprogramme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private Nullable<global::System.Int32> _service_id;
        partial void Onservice_idChanging(Nullable<global::System.Int32> value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> gapstart
        {
            get
            {
                return _gapstart;
            }
            set
            {
                OngapstartChanging(value);
                ReportPropertyChanging("gapstart");
                _gapstart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gapstart");
                OngapstartChanged();
            }
        }
        private Nullable<global::System.DateTime> _gapstart;
        partial void OngapstartChanging(Nullable<global::System.DateTime> value);
        partial void OngapstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> gapend
        {
            get
            {
                return _gapend;
            }
            set
            {
                OngapendChanging(value);
                ReportPropertyChanging("gapend");
                _gapend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gapend");
                OngapendChanged();
            }
        }
        private Nullable<global::System.DateTime> _gapend;
        partial void OngapendChanging(Nullable<global::System.DateTime> value);
        partial void OngapendChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="partialschedulematch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class partialschedulematch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new partialschedulematch object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static partialschedulematch Createpartialschedulematch(global::System.Int32 id)
        {
            partialschedulematch partialschedulematch = new partialschedulematch();
            partialschedulematch.id = id;
            return partialschedulematch;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                Onredux_idChanging(value);
                ReportPropertyChanging("redux_id");
                _redux_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("redux_id");
                Onredux_idChanged();
            }
        }
        private Nullable<global::System.Int32> _redux_id;
        partial void Onredux_idChanging(Nullable<global::System.Int32> value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                Onpips_idChanging(value);
                ReportPropertyChanging("pips_id");
                _pips_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pips_id");
                Onpips_idChanged();
            }
        }
        private Nullable<global::System.Int32> _pips_id;
        partial void Onpips_idChanging(Nullable<global::System.Int32> value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> overlap
        {
            get
            {
                return _overlap;
            }
            set
            {
                OnoverlapChanging(value);
                ReportPropertyChanging("overlap");
                _overlap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("overlap");
                OnoverlapChanged();
            }
        }
        private Nullable<global::System.DateTime> _overlap;
        partial void OnoverlapChanging(Nullable<global::System.DateTime> value);
        partial void OnoverlapChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="pips_programmes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pips_programmes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pips_programmes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static pips_programmes Createpips_programmes(global::System.Int32 id)
        {
            pips_programmes pips_programmes = new pips_programmes();
            pips_programmes.id = id;
            return pips_programmes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_name
        {
            get
            {
                return _programme_name;
            }
            set
            {
                Onprogramme_nameChanging(value);
                ReportPropertyChanging("programme_name");
                _programme_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_name");
                Onprogramme_nameChanged();
            }
        }
        private global::System.String _programme_name;
        partial void Onprogramme_nameChanging(global::System.String value);
        partial void Onprogramme_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String display_title
        {
            get
            {
                return _display_title;
            }
            set
            {
                Ondisplay_titleChanging(value);
                ReportPropertyChanging("display_title");
                _display_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("display_title");
                Ondisplay_titleChanged();
            }
        }
        private global::System.String _display_title;
        partial void Ondisplay_titleChanging(global::System.String value);
        partial void Ondisplay_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String display_subtitle
        {
            get
            {
                return _display_subtitle;
            }
            set
            {
                Ondisplay_subtitleChanging(value);
                ReportPropertyChanging("display_subtitle");
                _display_subtitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("display_subtitle");
                Ondisplay_subtitleChanged();
            }
        }
        private global::System.String _display_subtitle;
        partial void Ondisplay_subtitleChanging(global::System.String value);
        partial void Ondisplay_subtitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_time;
        partial void Onstart_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_time
        {
            get
            {
                return _end_time;
            }
            set
            {
                Onend_timeChanging(value);
                ReportPropertyChanging("end_time");
                _end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_time");
                Onend_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_time;
        partial void Onend_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onend_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private Nullable<global::System.Int32> _duration;
        partial void OndurationChanging(Nullable<global::System.Int32> value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private Nullable<global::System.Int32> _service_id;
        partial void Onservice_idChanging(Nullable<global::System.Int32> value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service_name
        {
            get
            {
                return _service_name;
            }
            set
            {
                Onservice_nameChanging(value);
                ReportPropertyChanging("service_name");
                _service_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service_name");
                Onservice_nameChanged();
            }
        }
        private global::System.String _service_name;
        partial void Onservice_nameChanging(global::System.String value);
        partial void Onservice_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> matched
        {
            get
            {
                return _matched;
            }
            set
            {
                OnmatchedChanging(value);
                ReportPropertyChanging("matched");
                _matched = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("matched");
                OnmatchedChanged();
            }
        }
        private Nullable<global::System.Int32> _matched;
        partial void OnmatchedChanging(Nullable<global::System.Int32> value);
        partial void OnmatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rawdata
        {
            get
            {
                return _rawdata;
            }
            set
            {
                OnrawdataChanging(value);
                ReportPropertyChanging("rawdata");
                _rawdata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rawdata");
                OnrawdataChanged();
            }
        }
        private global::System.String _rawdata;
        partial void OnrawdataChanging(global::System.String value);
        partial void OnrawdataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_gmt
        {
            get
            {
                return _start_gmt;
            }
            set
            {
                Onstart_gmtChanging(value);
                ReportPropertyChanging("start_gmt");
                _start_gmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_gmt");
                Onstart_gmtChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_gmt;
        partial void Onstart_gmtChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_gmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_gmt
        {
            get
            {
                return _end_gmt;
            }
            set
            {
                Onend_gmtChanging(value);
                ReportPropertyChanging("end_gmt");
                _end_gmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_gmt");
                Onend_gmtChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_gmt;
        partial void Onend_gmtChanging(Nullable<global::System.DateTime> value);
        partial void Onend_gmtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_items")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_items : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_items object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static redux_items Createredux_items(global::System.Int32 id)
        {
            redux_items redux_items = new redux_items();
            redux_items.id = id;
            return redux_items;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_name
        {
            get
            {
                return _programme_name;
            }
            set
            {
                Onprogramme_nameChanging(value);
                ReportPropertyChanging("programme_name");
                _programme_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_name");
                Onprogramme_nameChanged();
            }
        }
        private global::System.String _programme_name;
        partial void Onprogramme_nameChanging(global::System.String value);
        partial void Onprogramme_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String short_description
        {
            get
            {
                return _short_description;
            }
            set
            {
                Onshort_descriptionChanging(value);
                ReportPropertyChanging("short_description");
                _short_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("short_description");
                Onshort_descriptionChanged();
            }
        }
        private global::System.String _short_description;
        partial void Onshort_descriptionChanging(global::System.String value);
        partial void Onshort_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private Nullable<global::System.Int32> _duration;
        partial void OndurationChanging(Nullable<global::System.Int32> value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private Nullable<global::System.Int32> _service_id;
        partial void Onservice_idChanging(Nullable<global::System.Int32> value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> aired
        {
            get
            {
                return _aired;
            }
            set
            {
                OnairedChanging(value);
                ReportPropertyChanging("aired");
                _aired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aired");
                OnairedChanged();
            }
        }
        private Nullable<global::System.DateTime> _aired;
        partial void OnairedChanging(Nullable<global::System.DateTime> value);
        partial void OnairedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String disk_reference
        {
            get
            {
                return _disk_reference;
            }
            set
            {
                Ondisk_referenceChanging(value);
                ReportPropertyChanging("disk_reference");
                _disk_reference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("disk_reference");
                Ondisk_referenceChanged();
            }
        }
        private global::System.String _disk_reference;
        partial void Ondisk_referenceChanging(global::System.String value);
        partial void Ondisk_referenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_crid
        {
            get
            {
                return _programme_crid;
            }
            set
            {
                Onprogramme_cridChanging(value);
                ReportPropertyChanging("programme_crid");
                _programme_crid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_crid");
                Onprogramme_cridChanged();
            }
        }
        private global::System.String _programme_crid;
        partial void Onprogramme_cridChanging(global::System.String value);
        partial void Onprogramme_cridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String series_crid
        {
            get
            {
                return _series_crid;
            }
            set
            {
                Onseries_cridChanging(value);
                ReportPropertyChanging("series_crid");
                _series_crid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("series_crid");
                Onseries_cridChanged();
            }
        }
        private global::System.String _series_crid;
        partial void Onseries_cridChanging(global::System.String value);
        partial void Onseries_cridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> has_live_subtitles
        {
            get
            {
                return _has_live_subtitles;
            }
            set
            {
                Onhas_live_subtitlesChanging(value);
                ReportPropertyChanging("has_live_subtitles");
                _has_live_subtitles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("has_live_subtitles");
                Onhas_live_subtitlesChanged();
            }
        }
        private Nullable<global::System.Byte> _has_live_subtitles;
        partial void Onhas_live_subtitlesChanging(Nullable<global::System.Byte> value);
        partial void Onhas_live_subtitlesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_at;
        partial void Oncreated_atChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _updated_at;
        partial void Onupdated_atChanging(Nullable<global::System.DateTime> value);
        partial void Onupdated_atChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_to_pips")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_to_pips : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_to_pips object.
        /// </summary>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        public static redux_to_pips Createredux_to_pips(global::System.Int32 redux_id, global::System.Int32 pips_id)
        {
            redux_to_pips redux_to_pips = new redux_to_pips();
            redux_to_pips.redux_id = redux_id;
            redux_to_pips.pips_id = pips_id;
            return redux_to_pips;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                if (_redux_id != value)
                {
                    Onredux_idChanging(value);
                    ReportPropertyChanging("redux_id");
                    _redux_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("redux_id");
                    Onredux_idChanged();
                }
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                if (_pips_id != value)
                {
                    Onpips_idChanging(value);
                    ReportPropertyChanging("pips_id");
                    _pips_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pips_id");
                    Onpips_idChanged();
                }
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ischecked
        {
            get
            {
                return _ischecked;
            }
            set
            {
                OnischeckedChanging(value);
                ReportPropertyChanging("ischecked");
                _ischecked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ischecked");
                OnischeckedChanged();
            }
        }
        private Nullable<global::System.Int32> _ischecked;
        partial void OnischeckedChanging(Nullable<global::System.Int32> value);
        partial void OnischeckedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> title_match
        {
            get
            {
                return _title_match;
            }
            set
            {
                Ontitle_matchChanging(value);
                ReportPropertyChanging("title_match");
                _title_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("title_match");
                Ontitle_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _title_match;
        partial void Ontitle_matchChanging(Nullable<global::System.Int32> value);
        partial void Ontitle_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration_match
        {
            get
            {
                return _duration_match;
            }
            set
            {
                Onduration_matchChanging(value);
                ReportPropertyChanging("duration_match");
                _duration_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration_match");
                Onduration_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _duration_match;
        partial void Onduration_matchChanging(Nullable<global::System.Int32> value);
        partial void Onduration_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_match
        {
            get
            {
                return _start_match;
            }
            set
            {
                Onstart_matchChanging(value);
                ReportPropertyChanging("start_match");
                _start_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_match");
                Onstart_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _start_match;
        partial void Onstart_matchChanging(Nullable<global::System.Int32> value);
        partial void Onstart_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> partial_match
        {
            get
            {
                return _partial_match;
            }
            set
            {
                Onpartial_matchChanging(value);
                ReportPropertyChanging("partial_match");
                _partial_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("partial_match");
                Onpartial_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _partial_match;
        partial void Onpartial_matchChanging(Nullable<global::System.Int32> value);
        partial void Onpartial_matchChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_to_pipstoo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_to_pipstoo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_to_pipstoo object.
        /// </summary>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        public static redux_to_pipstoo Createredux_to_pipstoo(global::System.Int32 redux_id, global::System.Int32 pips_id)
        {
            redux_to_pipstoo redux_to_pipstoo = new redux_to_pipstoo();
            redux_to_pipstoo.redux_id = redux_id;
            redux_to_pipstoo.pips_id = pips_id;
            return redux_to_pipstoo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                if (_redux_id != value)
                {
                    Onredux_idChanging(value);
                    ReportPropertyChanging("redux_id");
                    _redux_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("redux_id");
                    Onredux_idChanged();
                }
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                if (_pips_id != value)
                {
                    Onpips_idChanging(value);
                    ReportPropertyChanging("pips_id");
                    _pips_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pips_id");
                    Onpips_idChanged();
                }
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ischecked
        {
            get
            {
                return _ischecked;
            }
            set
            {
                OnischeckedChanging(value);
                ReportPropertyChanging("ischecked");
                _ischecked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ischecked");
                OnischeckedChanged();
            }
        }
        private Nullable<global::System.Int32> _ischecked;
        partial void OnischeckedChanging(Nullable<global::System.Int32> value);
        partial void OnischeckedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> title_match
        {
            get
            {
                return _title_match;
            }
            set
            {
                Ontitle_matchChanging(value);
                ReportPropertyChanging("title_match");
                _title_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("title_match");
                Ontitle_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _title_match;
        partial void Ontitle_matchChanging(Nullable<global::System.Int32> value);
        partial void Ontitle_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration_match
        {
            get
            {
                return _duration_match;
            }
            set
            {
                Onduration_matchChanging(value);
                ReportPropertyChanging("duration_match");
                _duration_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration_match");
                Onduration_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _duration_match;
        partial void Onduration_matchChanging(Nullable<global::System.Int32> value);
        partial void Onduration_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_match
        {
            get
            {
                return _start_match;
            }
            set
            {
                Onstart_matchChanging(value);
                ReportPropertyChanging("start_match");
                _start_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_match");
                Onstart_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _start_match;
        partial void Onstart_matchChanging(Nullable<global::System.Int32> value);
        partial void Onstart_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> partial_match
        {
            get
            {
                return _partial_match;
            }
            set
            {
                Onpartial_matchChanging(value);
                ReportPropertyChanging("partial_match");
                _partial_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("partial_match");
                Onpartial_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _partial_match;
        partial void Onpartial_matchChanging(Nullable<global::System.Int32> value);
        partial void Onpartial_matchChanged();

        #endregion
    
    }

    #endregion
    
}
