//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MatchRedux
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReduxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReduxEntities object using the connection string found in the 'ReduxEntities' section of the application configuration file.
        /// </summary>
        public ReduxEntities() : base("name=ReduxEntities", "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReduxEntities object.
        /// </summary>
        public ReduxEntities(string connectionString) : base(connectionString, "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReduxEntities object.
        /// </summary>
        public ReduxEntities(EntityConnection connection) : base(connection, "ReduxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gap> gaps
        {
            get
            {
                if ((_gaps == null))
                {
                    _gaps = base.CreateObjectSet<gap>("gaps");
                }
                return _gaps;
            }
        }
        private ObjectSet<gap> _gaps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<partialschedulematch> partialschedulematches
        {
            get
            {
                if ((_partialschedulematches == null))
                {
                    _partialschedulematches = base.CreateObjectSet<partialschedulematch>("partialschedulematches");
                }
                return _partialschedulematches;
            }
        }
        private ObjectSet<partialschedulematch> _partialschedulematches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pips_programmes> pips_programmes
        {
            get
            {
                if ((_pips_programmes == null))
                {
                    _pips_programmes = base.CreateObjectSet<pips_programmes>("pips_programmes");
                }
                return _pips_programmes;
            }
        }
        private ObjectSet<pips_programmes> _pips_programmes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_items> redux_items
        {
            get
            {
                if ((_redux_items == null))
                {
                    _redux_items = base.CreateObjectSet<redux_items>("redux_items");
                }
                return _redux_items;
            }
        }
        private ObjectSet<redux_items> _redux_items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_to_pips> redux_to_pips
        {
            get
            {
                if ((_redux_to_pips == null))
                {
                    _redux_to_pips = base.CreateObjectSet<redux_to_pips>("redux_to_pips");
                }
                return _redux_to_pips;
            }
        }
        private ObjectSet<redux_to_pips> _redux_to_pips;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<redux_to_pipstoo> redux_to_pipstoo
        {
            get
            {
                if ((_redux_to_pipstoo == null))
                {
                    _redux_to_pipstoo = base.CreateObjectSet<redux_to_pipstoo>("redux_to_pipstoo");
                }
                return _redux_to_pipstoo;
            }
        }
        private ObjectSet<redux_to_pipstoo> _redux_to_pipstoo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<genre> genres
        {
            get
            {
                if ((_genres == null))
                {
                    _genres = base.CreateObjectSet<genre>("genres");
                }
                return _genres;
            }
        }
        private ObjectSet<genre> _genres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<genre_pids> genre_pids
        {
            get
            {
                if ((_genre_pids == null))
                {
                    _genre_pids = base.CreateObjectSet<genre_pids>("genre_pids");
                }
                return _genre_pids;
            }
        }
        private ObjectSet<genre_pids> _genre_pids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<scan_pips_contributors> scan_pips_contributors
        {
            get
            {
                if ((_scan_pips_contributors == null))
                {
                    _scan_pips_contributors = base.CreateObjectSet<scan_pips_contributors>("scan_pips_contributors");
                }
                return _scan_pips_contributors;
            }
        }
        private ObjectSet<scan_pips_contributors> _scan_pips_contributors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<contributor> contributors
        {
            get
            {
                if ((_contributors == null))
                {
                    _contributors = base.CreateObjectSet<contributor>("contributors");
                }
                return _contributors;
            }
        }
        private ObjectSet<contributor> _contributors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tag> tags
        {
            get
            {
                if ((_tags == null))
                {
                    _tags = base.CreateObjectSet<tag>("tags");
                }
                return _tags;
            }
        }
        private ObjectSet<tag> _tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<canonical> canonicals
        {
            get
            {
                if ((_canonicals == null))
                {
                    _canonicals = base.CreateObjectSet<canonical>("canonicals");
                }
                return _canonicals;
            }
        }
        private ObjectSet<canonical> _canonicals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogaps(gap gap)
        {
            base.AddObject("gaps", gap);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the partialschedulematches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopartialschedulematches(partialschedulematch partialschedulematch)
        {
            base.AddObject("partialschedulematches", partialschedulematch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pips_programmes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopips_programmes(pips_programmes pips_programmes)
        {
            base.AddObject("pips_programmes", pips_programmes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_items(redux_items redux_items)
        {
            base.AddObject("redux_items", redux_items);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_to_pips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_to_pips(redux_to_pips redux_to_pips)
        {
            base.AddObject("redux_to_pips", redux_to_pips);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the redux_to_pipstoo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToredux_to_pipstoo(redux_to_pipstoo redux_to_pipstoo)
        {
            base.AddObject("redux_to_pipstoo", redux_to_pipstoo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the genres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogenres(genre genre)
        {
            base.AddObject("genres", genre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the genre_pids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogenre_pids(genre_pids genre_pids)
        {
            base.AddObject("genre_pids", genre_pids);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the scan_pips_contributors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToscan_pips_contributors(scan_pips_contributors scan_pips_contributors)
        {
            base.AddObject("scan_pips_contributors", scan_pips_contributors);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contributors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontributors(contributor contributor)
        {
            base.AddObject("contributors", contributor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotags(tag tag)
        {
            base.AddObject("tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the canonicals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocanonicals(canonical canonical)
        {
            base.AddObject("canonicals", canonical);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="canonical")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class canonical : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new canonical object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="isCanonical">Initial value of the IsCanonical property.</param>
        public static canonical Createcanonical(global::System.Int32 id, global::System.Int32 redux_id, global::System.Boolean isCanonical)
        {
            canonical canonical = new canonical();
            canonical.id = id;
            canonical.redux_id = redux_id;
            canonical.IsCanonical = isCanonical;
            return canonical;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                Onredux_idChanging(value);
                ReportPropertyChanging("redux_id");
                _redux_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("redux_id");
                Onredux_idChanged();
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCanonical
        {
            get
            {
                return _IsCanonical;
            }
            set
            {
                OnIsCanonicalChanging(value);
                ReportPropertyChanging("IsCanonical");
                _IsCanonical = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCanonical");
                OnIsCanonicalChanged();
            }
        }
        private global::System.Boolean _IsCanonical;
        partial void OnIsCanonicalChanging(global::System.Boolean value);
        partial void OnIsCanonicalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static category Createcategory(global::System.Int32 id)
        {
            category category = new category();
            category.id = id;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String catkey
        {
            get
            {
                return _catkey;
            }
            set
            {
                OncatkeyChanging(value);
                ReportPropertyChanging("catkey");
                _catkey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("catkey");
                OncatkeyChanged();
            }
        }
        private global::System.String _catkey;
        partial void OncatkeyChanging(global::System.String value);
        partial void OncatkeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="contributor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class contributor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new contributor object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="contributor_id">Initial value of the contributor_id property.</param>
        public static contributor Createcontributor(global::System.Int32 id, global::System.Int32 contributor_id)
        {
            contributor contributor = new contributor();
            contributor.id = id;
            contributor.contributor_id = contributor_id;
            return contributor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String character_name
        {
            get
            {
                return _character_name;
            }
            set
            {
                Oncharacter_nameChanging(value);
                ReportPropertyChanging("character_name");
                _character_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("character_name");
                Oncharacter_nameChanged();
            }
        }
        private global::System.String _character_name;
        partial void Oncharacter_nameChanging(global::System.String value);
        partial void Oncharacter_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String family_name
        {
            get
            {
                return _family_name;
            }
            set
            {
                Onfamily_nameChanging(value);
                ReportPropertyChanging("family_name");
                _family_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("family_name");
                Onfamily_nameChanged();
            }
        }
        private global::System.String _family_name;
        partial void Onfamily_nameChanging(global::System.String value);
        partial void Onfamily_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String given_name
        {
            get
            {
                return _given_name;
            }
            set
            {
                Ongiven_nameChanging(value);
                ReportPropertyChanging("given_name");
                _given_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("given_name");
                Ongiven_nameChanged();
            }
        }
        private global::System.String _given_name;
        partial void Ongiven_nameChanging(global::System.String value);
        partial void Ongiven_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 contributor_id
        {
            get
            {
                return _contributor_id;
            }
            set
            {
                Oncontributor_idChanging(value);
                ReportPropertyChanging("contributor_id");
                _contributor_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("contributor_id");
                Oncontributor_idChanged();
            }
        }
        private global::System.Int32 _contributor_id;
        partial void Oncontributor_idChanging(global::System.Int32 value);
        partial void Oncontributor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.String _role;
        partial void OnroleChanging(global::System.String value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String role_name
        {
            get
            {
                return _role_name;
            }
            set
            {
                Onrole_nameChanging(value);
                ReportPropertyChanging("role_name");
                _role_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("role_name");
                Onrole_nameChanged();
            }
        }
        private global::System.String _role_name;
        partial void Onrole_nameChanging(global::System.String value);
        partial void Onrole_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="gap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gap object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="programme_id">Initial value of the programme_id property.</param>
        /// <param name="service_id">Initial value of the service_id property.</param>
        /// <param name="gapstart">Initial value of the gapstart property.</param>
        /// <param name="gapend">Initial value of the gapend property.</param>
        public static gap Creategap(global::System.Int32 id, global::System.Int32 programme_id, global::System.Int32 service_id, global::System.DateTime gapstart, global::System.DateTime gapend)
        {
            gap gap = new gap();
            gap.id = id;
            gap.programme_id = programme_id;
            gap.service_id = service_id;
            gap.gapstart = gapstart;
            gap.gapend = gapend;
            return gap;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 programme_id
        {
            get
            {
                return _programme_id;
            }
            set
            {
                Onprogramme_idChanging(value);
                ReportPropertyChanging("programme_id");
                _programme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("programme_id");
                Onprogramme_idChanged();
            }
        }
        private global::System.Int32 _programme_id;
        partial void Onprogramme_idChanging(global::System.Int32 value);
        partial void Onprogramme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private global::System.Int32 _service_id;
        partial void Onservice_idChanging(global::System.Int32 value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime gapstart
        {
            get
            {
                return _gapstart;
            }
            set
            {
                OngapstartChanging(value);
                ReportPropertyChanging("gapstart");
                _gapstart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gapstart");
                OngapstartChanged();
            }
        }
        private global::System.DateTime _gapstart;
        partial void OngapstartChanging(global::System.DateTime value);
        partial void OngapstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime gapend
        {
            get
            {
                return _gapend;
            }
            set
            {
                OngapendChanging(value);
                ReportPropertyChanging("gapend");
                _gapend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gapend");
                OngapendChanged();
            }
        }
        private global::System.DateTime _gapend;
        partial void OngapendChanging(global::System.DateTime value);
        partial void OngapendChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="genre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class genre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new genre object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        public static genre Creategenre(global::System.Int32 id, global::System.Int32 pips_id)
        {
            genre genre = new genre();
            genre.id = id;
            genre.pips_id = pips_id;
            return genre;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                Onpips_idChanging(value);
                ReportPropertyChanging("pips_id");
                _pips_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pips_id");
                Onpips_idChanged();
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="genre_pids")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class genre_pids : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new genre_pids object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static genre_pids Creategenre_pids(global::System.Int32 id)
        {
            genre_pids genre_pids = new genre_pids();
            genre_pids.id = id;
            return genre_pids;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="partialschedulematch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class partialschedulematch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new partialschedulematch object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        /// <param name="overlap">Initial value of the overlap property.</param>
        public static partialschedulematch Createpartialschedulematch(global::System.Int32 id, global::System.Int32 redux_id, global::System.Int32 pips_id, global::System.DateTime overlap)
        {
            partialschedulematch partialschedulematch = new partialschedulematch();
            partialschedulematch.id = id;
            partialschedulematch.redux_id = redux_id;
            partialschedulematch.pips_id = pips_id;
            partialschedulematch.overlap = overlap;
            return partialschedulematch;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                Onredux_idChanging(value);
                ReportPropertyChanging("redux_id");
                _redux_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("redux_id");
                Onredux_idChanged();
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                Onpips_idChanging(value);
                ReportPropertyChanging("pips_id");
                _pips_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pips_id");
                Onpips_idChanged();
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime overlap
        {
            get
            {
                return _overlap;
            }
            set
            {
                OnoverlapChanging(value);
                ReportPropertyChanging("overlap");
                _overlap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("overlap");
                OnoverlapChanged();
            }
        }
        private global::System.DateTime _overlap;
        partial void OnoverlapChanging(global::System.DateTime value);
        partial void OnoverlapChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="pips_programmes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pips_programmes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pips_programmes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="start_time">Initial value of the start_time property.</param>
        /// <param name="end_time">Initial value of the end_time property.</param>
        /// <param name="duration">Initial value of the duration property.</param>
        /// <param name="service_id">Initial value of the service_id property.</param>
        /// <param name="matched">Initial value of the matched property.</param>
        /// <param name="start_gmt">Initial value of the start_gmt property.</param>
        /// <param name="end_gmt">Initial value of the end_gmt property.</param>
        public static pips_programmes Createpips_programmes(global::System.Int32 id, global::System.DateTime start_time, global::System.DateTime end_time, global::System.Int32 duration, global::System.Int32 service_id, global::System.Int32 matched, global::System.DateTime start_gmt, global::System.DateTime end_gmt)
        {
            pips_programmes pips_programmes = new pips_programmes();
            pips_programmes.id = id;
            pips_programmes.start_time = start_time;
            pips_programmes.end_time = end_time;
            pips_programmes.duration = duration;
            pips_programmes.service_id = service_id;
            pips_programmes.matched = matched;
            pips_programmes.start_gmt = start_gmt;
            pips_programmes.end_gmt = end_gmt;
            return pips_programmes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_name
        {
            get
            {
                return _programme_name;
            }
            set
            {
                Onprogramme_nameChanging(value);
                ReportPropertyChanging("programme_name");
                _programme_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_name");
                Onprogramme_nameChanged();
            }
        }
        private global::System.String _programme_name;
        partial void Onprogramme_nameChanging(global::System.String value);
        partial void Onprogramme_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String display_title
        {
            get
            {
                return _display_title;
            }
            set
            {
                Ondisplay_titleChanging(value);
                ReportPropertyChanging("display_title");
                _display_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("display_title");
                Ondisplay_titleChanged();
            }
        }
        private global::System.String _display_title;
        partial void Ondisplay_titleChanging(global::System.String value);
        partial void Ondisplay_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String display_subtitle
        {
            get
            {
                return _display_subtitle;
            }
            set
            {
                Ondisplay_subtitleChanging(value);
                ReportPropertyChanging("display_subtitle");
                _display_subtitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("display_subtitle");
                Ondisplay_subtitleChanged();
            }
        }
        private global::System.String _display_subtitle;
        partial void Ondisplay_subtitleChanging(global::System.String value);
        partial void Ondisplay_subtitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private global::System.DateTime _start_time;
        partial void Onstart_timeChanging(global::System.DateTime value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime end_time
        {
            get
            {
                return _end_time;
            }
            set
            {
                Onend_timeChanging(value);
                ReportPropertyChanging("end_time");
                _end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_time");
                Onend_timeChanged();
            }
        }
        private global::System.DateTime _end_time;
        partial void Onend_timeChanging(global::System.DateTime value);
        partial void Onend_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private global::System.Int32 _duration;
        partial void OndurationChanging(global::System.Int32 value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private global::System.Int32 _service_id;
        partial void Onservice_idChanging(global::System.Int32 value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String service_name
        {
            get
            {
                return _service_name;
            }
            set
            {
                Onservice_nameChanging(value);
                ReportPropertyChanging("service_name");
                _service_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("service_name");
                Onservice_nameChanged();
            }
        }
        private global::System.String _service_name;
        partial void Onservice_nameChanging(global::System.String value);
        partial void Onservice_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 matched
        {
            get
            {
                return _matched;
            }
            set
            {
                OnmatchedChanging(value);
                ReportPropertyChanging("matched");
                _matched = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("matched");
                OnmatchedChanged();
            }
        }
        private global::System.Int32 _matched;
        partial void OnmatchedChanging(global::System.Int32 value);
        partial void OnmatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rawdata
        {
            get
            {
                return _rawdata;
            }
            set
            {
                OnrawdataChanging(value);
                ReportPropertyChanging("rawdata");
                _rawdata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rawdata");
                OnrawdataChanged();
            }
        }
        private global::System.String _rawdata;
        partial void OnrawdataChanging(global::System.String value);
        partial void OnrawdataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start_gmt
        {
            get
            {
                return _start_gmt;
            }
            set
            {
                Onstart_gmtChanging(value);
                ReportPropertyChanging("start_gmt");
                _start_gmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_gmt");
                Onstart_gmtChanged();
            }
        }
        private global::System.DateTime _start_gmt;
        partial void Onstart_gmtChanging(global::System.DateTime value);
        partial void Onstart_gmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime end_gmt
        {
            get
            {
                return _end_gmt;
            }
            set
            {
                Onend_gmtChanging(value);
                ReportPropertyChanging("end_gmt");
                _end_gmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_gmt");
                Onend_gmtChanged();
            }
        }
        private global::System.DateTime _end_gmt;
        partial void Onend_gmtChanging(global::System.DateTime value);
        partial void Onend_gmtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_items")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_items : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_items object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="duration">Initial value of the duration property.</param>
        /// <param name="service_id">Initial value of the service_id property.</param>
        /// <param name="aired">Initial value of the aired property.</param>
        /// <param name="has_live_subtitles">Initial value of the has_live_subtitles property.</param>
        /// <param name="created_at">Initial value of the created_at property.</param>
        /// <param name="updated_at">Initial value of the updated_at property.</param>
        public static redux_items Createredux_items(global::System.Int32 id, global::System.Int32 duration, global::System.Int32 service_id, global::System.DateTime aired, global::System.Boolean has_live_subtitles, global::System.DateTime created_at, global::System.DateTime updated_at)
        {
            redux_items redux_items = new redux_items();
            redux_items.id = id;
            redux_items.duration = duration;
            redux_items.service_id = service_id;
            redux_items.aired = aired;
            redux_items.has_live_subtitles = has_live_subtitles;
            redux_items.created_at = created_at;
            redux_items.updated_at = updated_at;
            return redux_items;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_name
        {
            get
            {
                return _programme_name;
            }
            set
            {
                Onprogramme_nameChanging(value);
                ReportPropertyChanging("programme_name");
                _programme_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_name");
                Onprogramme_nameChanged();
            }
        }
        private global::System.String _programme_name;
        partial void Onprogramme_nameChanging(global::System.String value);
        partial void Onprogramme_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String short_description
        {
            get
            {
                return _short_description;
            }
            set
            {
                Onshort_descriptionChanging(value);
                ReportPropertyChanging("short_description");
                _short_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("short_description");
                Onshort_descriptionChanged();
            }
        }
        private global::System.String _short_description;
        partial void Onshort_descriptionChanging(global::System.String value);
        partial void Onshort_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private global::System.Int32 _duration;
        partial void OndurationChanging(global::System.Int32 value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 service_id
        {
            get
            {
                return _service_id;
            }
            set
            {
                Onservice_idChanging(value);
                ReportPropertyChanging("service_id");
                _service_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("service_id");
                Onservice_idChanged();
            }
        }
        private global::System.Int32 _service_id;
        partial void Onservice_idChanging(global::System.Int32 value);
        partial void Onservice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime aired
        {
            get
            {
                return _aired;
            }
            set
            {
                OnairedChanging(value);
                ReportPropertyChanging("aired");
                _aired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aired");
                OnairedChanged();
            }
        }
        private global::System.DateTime _aired;
        partial void OnairedChanging(global::System.DateTime value);
        partial void OnairedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String disk_reference
        {
            get
            {
                return _disk_reference;
            }
            set
            {
                Ondisk_referenceChanging(value);
                ReportPropertyChanging("disk_reference");
                _disk_reference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("disk_reference");
                Ondisk_referenceChanged();
            }
        }
        private global::System.String _disk_reference;
        partial void Ondisk_referenceChanging(global::System.String value);
        partial void Ondisk_referenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String programme_crid
        {
            get
            {
                return _programme_crid;
            }
            set
            {
                Onprogramme_cridChanging(value);
                ReportPropertyChanging("programme_crid");
                _programme_crid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("programme_crid");
                Onprogramme_cridChanged();
            }
        }
        private global::System.String _programme_crid;
        partial void Onprogramme_cridChanging(global::System.String value);
        partial void Onprogramme_cridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String series_crid
        {
            get
            {
                return _series_crid;
            }
            set
            {
                Onseries_cridChanging(value);
                ReportPropertyChanging("series_crid");
                _series_crid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("series_crid");
                Onseries_cridChanged();
            }
        }
        private global::System.String _series_crid;
        partial void Onseries_cridChanging(global::System.String value);
        partial void Onseries_cridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean has_live_subtitles
        {
            get
            {
                return _has_live_subtitles;
            }
            set
            {
                Onhas_live_subtitlesChanging(value);
                ReportPropertyChanging("has_live_subtitles");
                _has_live_subtitles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("has_live_subtitles");
                Onhas_live_subtitlesChanged();
            }
        }
        private global::System.Boolean _has_live_subtitles;
        partial void Onhas_live_subtitlesChanging(global::System.Boolean value);
        partial void Onhas_live_subtitlesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.DateTime _created_at;
        partial void Oncreated_atChanging(global::System.DateTime value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private global::System.DateTime _updated_at;
        partial void Onupdated_atChanging(global::System.DateTime value);
        partial void Onupdated_atChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_to_pips")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_to_pips : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_to_pips object.
        /// </summary>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        /// <param name="ischecked">Initial value of the ischecked property.</param>
        /// <param name="title_match">Initial value of the title_match property.</param>
        /// <param name="duration_match">Initial value of the duration_match property.</param>
        /// <param name="start_match">Initial value of the start_match property.</param>
        /// <param name="partial_match">Initial value of the partial_match property.</param>
        public static redux_to_pips Createredux_to_pips(global::System.Int32 redux_id, global::System.Int32 pips_id, global::System.Boolean ischecked, global::System.Boolean title_match, global::System.Boolean duration_match, global::System.Boolean start_match, global::System.Boolean partial_match)
        {
            redux_to_pips redux_to_pips = new redux_to_pips();
            redux_to_pips.redux_id = redux_id;
            redux_to_pips.pips_id = pips_id;
            redux_to_pips.ischecked = ischecked;
            redux_to_pips.title_match = title_match;
            redux_to_pips.duration_match = duration_match;
            redux_to_pips.start_match = start_match;
            redux_to_pips.partial_match = partial_match;
            return redux_to_pips;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                if (_redux_id != value)
                {
                    Onredux_idChanging(value);
                    ReportPropertyChanging("redux_id");
                    _redux_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("redux_id");
                    Onredux_idChanged();
                }
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                if (_pips_id != value)
                {
                    Onpips_idChanging(value);
                    ReportPropertyChanging("pips_id");
                    _pips_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pips_id");
                    Onpips_idChanged();
                }
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ischecked
        {
            get
            {
                return _ischecked;
            }
            set
            {
                OnischeckedChanging(value);
                ReportPropertyChanging("ischecked");
                _ischecked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ischecked");
                OnischeckedChanged();
            }
        }
        private global::System.Boolean _ischecked;
        partial void OnischeckedChanging(global::System.Boolean value);
        partial void OnischeckedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean title_match
        {
            get
            {
                return _title_match;
            }
            set
            {
                Ontitle_matchChanging(value);
                ReportPropertyChanging("title_match");
                _title_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("title_match");
                Ontitle_matchChanged();
            }
        }
        private global::System.Boolean _title_match;
        partial void Ontitle_matchChanging(global::System.Boolean value);
        partial void Ontitle_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean duration_match
        {
            get
            {
                return _duration_match;
            }
            set
            {
                Onduration_matchChanging(value);
                ReportPropertyChanging("duration_match");
                _duration_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration_match");
                Onduration_matchChanged();
            }
        }
        private global::System.Boolean _duration_match;
        partial void Onduration_matchChanging(global::System.Boolean value);
        partial void Onduration_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean start_match
        {
            get
            {
                return _start_match;
            }
            set
            {
                Onstart_matchChanging(value);
                ReportPropertyChanging("start_match");
                _start_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_match");
                Onstart_matchChanged();
            }
        }
        private global::System.Boolean _start_match;
        partial void Onstart_matchChanging(global::System.Boolean value);
        partial void Onstart_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean partial_match
        {
            get
            {
                return _partial_match;
            }
            set
            {
                Onpartial_matchChanging(value);
                ReportPropertyChanging("partial_match");
                _partial_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("partial_match");
                Onpartial_matchChanged();
            }
        }
        private global::System.Boolean _partial_match;
        partial void Onpartial_matchChanging(global::System.Boolean value);
        partial void Onpartial_matchChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="redux_to_pipstoo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class redux_to_pipstoo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new redux_to_pipstoo object.
        /// </summary>
        /// <param name="redux_id">Initial value of the redux_id property.</param>
        /// <param name="pips_id">Initial value of the pips_id property.</param>
        public static redux_to_pipstoo Createredux_to_pipstoo(global::System.Int32 redux_id, global::System.Int32 pips_id)
        {
            redux_to_pipstoo redux_to_pipstoo = new redux_to_pipstoo();
            redux_to_pipstoo.redux_id = redux_id;
            redux_to_pipstoo.pips_id = pips_id;
            return redux_to_pipstoo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redux_id
        {
            get
            {
                return _redux_id;
            }
            set
            {
                if (_redux_id != value)
                {
                    Onredux_idChanging(value);
                    ReportPropertyChanging("redux_id");
                    _redux_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("redux_id");
                    Onredux_idChanged();
                }
            }
        }
        private global::System.Int32 _redux_id;
        partial void Onredux_idChanging(global::System.Int32 value);
        partial void Onredux_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pips_id
        {
            get
            {
                return _pips_id;
            }
            set
            {
                if (_pips_id != value)
                {
                    Onpips_idChanging(value);
                    ReportPropertyChanging("pips_id");
                    _pips_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pips_id");
                    Onpips_idChanged();
                }
            }
        }
        private global::System.Int32 _pips_id;
        partial void Onpips_idChanging(global::System.Int32 value);
        partial void Onpips_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ischecked
        {
            get
            {
                return _ischecked;
            }
            set
            {
                OnischeckedChanging(value);
                ReportPropertyChanging("ischecked");
                _ischecked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ischecked");
                OnischeckedChanged();
            }
        }
        private Nullable<global::System.Int32> _ischecked;
        partial void OnischeckedChanging(Nullable<global::System.Int32> value);
        partial void OnischeckedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> title_match
        {
            get
            {
                return _title_match;
            }
            set
            {
                Ontitle_matchChanging(value);
                ReportPropertyChanging("title_match");
                _title_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("title_match");
                Ontitle_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _title_match;
        partial void Ontitle_matchChanging(Nullable<global::System.Int32> value);
        partial void Ontitle_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duration_match
        {
            get
            {
                return _duration_match;
            }
            set
            {
                Onduration_matchChanging(value);
                ReportPropertyChanging("duration_match");
                _duration_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration_match");
                Onduration_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _duration_match;
        partial void Onduration_matchChanging(Nullable<global::System.Int32> value);
        partial void Onduration_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_match
        {
            get
            {
                return _start_match;
            }
            set
            {
                Onstart_matchChanging(value);
                ReportPropertyChanging("start_match");
                _start_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_match");
                Onstart_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _start_match;
        partial void Onstart_matchChanging(Nullable<global::System.Int32> value);
        partial void Onstart_matchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> partial_match
        {
            get
            {
                return _partial_match;
            }
            set
            {
                Onpartial_matchChanging(value);
                ReportPropertyChanging("partial_match");
                _partial_match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("partial_match");
                Onpartial_matchChanged();
            }
        }
        private Nullable<global::System.Int32> _partial_match;
        partial void Onpartial_matchChanging(Nullable<global::System.Int32> value);
        partial void Onpartial_matchChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="scan_pips_contributors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class scan_pips_contributors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new scan_pips_contributors object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        /// <param name="scanned">Initial value of the scanned property.</param>
        public static scan_pips_contributors Createscan_pips_contributors(global::System.String pid, global::System.Boolean scanned)
        {
            scan_pips_contributors scan_pips_contributors = new scan_pips_contributors();
            scan_pips_contributors.pid = pid;
            scan_pips_contributors.scanned = scanned;
            return scan_pips_contributors;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean scanned
        {
            get
            {
                return _scanned;
            }
            set
            {
                OnscannedChanging(value);
                ReportPropertyChanging("scanned");
                _scanned = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("scanned");
                OnscannedChanged();
            }
        }
        private global::System.Boolean _scanned;
        partial void OnscannedChanging(global::System.Boolean value);
        partial void OnscannedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReduxItems", Name="tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tag object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tag Createtag(global::System.Int32 id)
        {
            tag tag = new tag();
            tag.id = id;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tag_id
        {
            get
            {
                return _tag_id;
            }
            set
            {
                Ontag_idChanging(value);
                ReportPropertyChanging("tag_id");
                _tag_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tag_id");
                Ontag_idChanged();
            }
        }
        private global::System.String _tag_id;
        partial void Ontag_idChanging(global::System.String value);
        partial void Ontag_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
    }

    #endregion
    
}
